kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
  - containerPort: 32000
    hostPort: 32000
    protocol: TCP
  - containerPort: 32001
    hostPort: 32001
    protocol: TCP
  - containerPort: 32002
    hostPort: 32002
    protocol: TCP
  - containerPort: 32003
    hostPort: 32003
    protocol: TCP
  - containerPort: 32004
    hostPort: 32004
    protocol: TCP
  - containerPort: 32005
    hostPort: 32005
    protocol: TCP
- role: worker
- role: worker

