apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticationapp
  template:
    metadata:
      labels:
        app: authenticationapp
    spec:
      containers:
        - name: authenticationapp
          image: alexandraion226/cloud-authentication-image
          env:
            - name: DATABASE_INTREACTION_URL
              value: http://dbinteraction.default.svc.cluster.local:8081/
          ports:
            - containerPort: 8082                      # Expose the port
              protocol: TCP
      hostname: authenticationapp
      restartPolicy: Always