apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-stack.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: authenticationapp
  name: authenticationapp
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: authenticationapp
