apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticationapp
  template:
    metadata:
      labels:
        app: authenticationapp
    spec:
      containers:
        - image: artemizadospinescu/authentication_image
          name: authenticationapp
          ports:
            - containerPort: 8082
              protocol: TCP
      hostname: authenticationapp
      restartPolicy: Always
