apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-stack.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: authenticationapp
  name: authenticationapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authenticationapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-stack.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: authenticationapp
    spec:
      containers:
        - image: artemizadospinescu/authentication_image
          name: authenticationapp
          ports:
            - containerPort: 8082
              protocol: TCP
      hostname: authenticationapp
      restartPolicy: Always
