apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-stack.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backendapp
  name: backendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backendapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-stack.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backendapp
    spec:
      containers:
        - image: artemizadospinescu/backend_image
          name: backendapp
          ports:
            - containerPort: 8083
              protocol: TCP
      hostname: backendapp
      restartPolicy: Always
