apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-stack.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backendapp
  name: backendapp
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: backendapp
