apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backendapp
  name: backendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
        - image: artemizadospinescu/backend_image
          name: backendapp
          ports:
            - containerPort: 8083
              protocol: TCP
      hostname: backendapp
      restartPolicy: Always
