apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backendapp
  name: backendapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
        - image: alexandraion226/cloud-bussiness-logic-image
          name: backendapp
          env:
            - name: DATABASE_INTREACTION_URL
              value: http://dbinteraction.default.svc.cluster.local:8081/
          ports:
            - containerPort: 8083
              protocol: TCP
      hostname: backendapp
      restartPolicy: Always
