apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-stack.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: dbinteraction
  name: dbinteraction
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dbinteraction
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-stack.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: dbinteraction
    spec:
      containers:
        - env:
            - name: DATABASE_PASSWORD
              value: admin
            - name: DATABASE_URL
              value: jdbc:postgresql://postgresdb:5432/gourmet-db
            - name: DATABASE_USERNAME
              value: postgres
          image: artemizadospinescu/db_interaction_image
          name: dbinteraction
          ports:
            - containerPort: 8081
              protocol: TCP
      hostname: dbinteraction
      restartPolicy: Always
