apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-stack.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: dbinteraction
  name: dbinteraction
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: dbinteraction
