apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbinteraction
  name: dbinteraction
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbinteraction
  template:
    metadata:
      labels:
        app: dbinteraction
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "until nc -z -v -w30 postgresdb 5432; do echo 'Waiting for database...'; sleep 5; done;"
          resources:
            limits:
              memory: "50Mi"
              cpu: "50m"
            requests:
              memory: "50Mi"
              cpu: "50m"
      containers:
        - env:
            - name: DATABASE_PASSWORD
              value: admin
            - name: DATABASE_URL
              value: jdbc:postgresql://postgresdb:5432/gourmet-db
            - name: DATABASE_USERNAME
              value: postgres
          image: alexandraion226/cloud-db-interaction-image
          name: dbinteraction
          ports:
            - containerPort: 8081
              protocol: TCP
      hostname: dbinteraction
      restartPolicy: Always