apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana-claim1
  name: grafana-claim1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
