apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin4
  name: pgadmin4
spec:
  type: NodePort
  ports:
    - name: "8086"
      port: 8086
      targetPort: 80
      nodePort: 32002
  selector:
    app: pgadmin4
