apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresdb
  name: postgresdb
  namespace: default
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: postgresdb
